# Generated by Django 5.2.1 on 2025-05-26 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название отделения')),
                ('bio', models.TextField(verbose_name='Краткое описание')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='departments/', verbose_name='Фото')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Отдел',
                'verbose_name_plural': 'Отделы',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(verbose_name='Вопрос')),
                ('answer', models.CharField(verbose_name='Ответ')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQ',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='gallery/')),
            ],
            options={
                'verbose_name': 'Галерея',
                'verbose_name_plural': 'Фото',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название услуги')),
                ('description', models.TextField(verbose_name='Описание')),
                ('icon', models.CharField(blank=True, null=True, verbose_name='Иконка')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, null=True, verbose_name='Имя')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram')),
                ('whatsapp', models.URLField(blank=True, null=True, verbose_name='Whatsapp')),
                ('telegram', models.URLField(blank=True, null=True, verbose_name='Telegram')),
            ],
            options={
                'verbose_name': 'Социальная сеть',
                'verbose_name_plural': 'Социальные сети',
            },
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Название заголовка')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='URL')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='doctors/', verbose_name='Фото')),
                ('bio', models.TextField(verbose_name='Биография')),
                ('experience_years', models.PositiveIntegerField(default=0, verbose_name='Стаж (в годах)')),
                ('education', models.TextField(blank=True, verbose_name='Образование')),
                ('price_per_consultation', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Цена за приём')),
                ('rating', models.FloatField(default=0, verbose_name='Рейтинг')),
                ('special_services', models.TextField(blank=True, verbose_name='Специальные услуги')),
                ('seo_description', models.CharField(blank=True, max_length=160, verbose_name='SEO описание')),
                ('accepts_online', models.BooleanField(default=False, verbose_name='Онлайн-консультации')),
                ('appointments_url', models.CharField(blank=True, null=True, verbose_name='Ссылка на запись')),
                ('video_presentation', models.URLField(blank=True, null=True, verbose_name='Видео-презентация')),
                ('working_days', models.CharField(blank=True, max_length=100, verbose_name='Рабочие дни')),
                ('working_hours', models.CharField(blank=True, max_length=100, verbose_name='Рабочие часы')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Мужской'), ('female', 'Женский')], max_length=10, verbose_name='Пол')),
                ('available', models.BooleanField(default=True, verbose_name='Доступен')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.departments', verbose_name='Специализация')),
                ('social_links', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinic.socialnetwork', verbose_name='Соц. сети')),
            ],
            options={
                'verbose_name': 'Врач',
                'verbose_name_plural': 'Врачи',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Имя пациента')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='E-mail')),
                ('phone', models.CharField(max_length=20, null=True, verbose_name='Номер телефона')),
                ('date', models.DateTimeField(null=True, verbose_name='Дата')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Сообщение')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic.departments', verbose_name='Отдел')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic.doctor', verbose_name='Врач')),
            ],
            options={
                'verbose_name': 'Запись на прием',
                'verbose_name_plural': 'Записи на прием',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('rating', models.PositiveSmallIntegerField(default=5, verbose_name='Рейтинг')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.doctor', verbose_name='Врач')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя пациента')),
                ('stars', models.PositiveSmallIntegerField(default=5, verbose_name='Оценка (звезды)')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('image', models.ImageField(blank=True, null=True, upload_to='testimonials/', verbose_name='Фото пациента')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.departments', verbose_name='Отделение')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.doctor', verbose_name='Врач')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
