# Generated by Django 5.2.1 on 2025-05-19 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_alter_appointment_options_alter_doctor_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='photo',
            field=models.ImageField(blank=True, default='img/default_user.png', null=True, upload_to='doctors/', verbose_name='Фото'),
        ),
    ]
