# Generated by Django 5.2.1 on 2025-05-19 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_alter_doctor_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='social_network_instagram',
            field=models.CharField(blank=True, verbose_name='Инстаграм'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='doctors/', verbose_name='Фото'),
        ),
    ]
