# Generated by Django 5.2.1 on 2025-05-20 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0005_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Название отделения')),
                ('bio', models.CharField(verbose_name='Краткое описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='departments/', verbose_name='Фото')),
                ('description', models.CharField(verbose_name='Описание')),
            ],
        ),
    ]
