# Generated by Django 5.2.1 on 2025-05-20 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0006_departments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departments',
            options={'verbose_name': 'Отдел', 'verbose_name_plural': 'Отделы'},
        ),
        migrations.RenameField(
            model_name='departments',
            old_name='image',
            new_name='photo',
        ),
    ]
