# Generated by Django 5.2.1 on 2025-05-20 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0007_alter_departments_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name': 'FAQ', 'verbose_name_plural': 'FAQ'},
        ),
        migrations.AddField(
            model_name='service',
            name='icon',
            field=models.CharField(blank=True, null=True, verbose_name='Иконка'),
        ),
    ]
