# Generated by Django 5.2.1 on 2025-05-20 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0010_socialnetwork_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Название заголовка')),
                ('description', models.CharField(verbose_name='Описание')),
            ],
        ),
    ]
