# Generated by Django 5.2.1 on 2025-05-20 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0012_remove_appointment_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='social_links',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinic.socialnetwork'),
        ),
    ]
