# Generated by Django 5.2.1 on 2025-05-21 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0013_alter_doctor_social_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='accepts_online',
            field=models.BooleanField(default=False, verbose_name='Онлайн-консультации'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='appointments_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на запись'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='education',
            field=models.TextField(blank=True, verbose_name='Образование'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='experience_years',
            field=models.PositiveIntegerField(default=0, verbose_name='Стаж (в годах)'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Мужской'), ('female', 'Женский')], max_length=10, verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='price_per_consultation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Цена за приём'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='rating',
            field=models.FloatField(default=0, verbose_name='Рейтинг'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='seo_description',
            field=models.CharField(blank=True, max_length=160, verbose_name='SEO описание'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='special_services',
            field=models.TextField(blank=True, verbose_name='Специальные услуги'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='video_presentation',
            field=models.URLField(blank=True, null=True, verbose_name='Видео-презентация'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='working_days',
            field=models.CharField(blank=True, max_length=100, verbose_name='Рабочие дни'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='working_hours',
            field=models.CharField(blank=True, max_length=100, verbose_name='Рабочие часы'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='social_links',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinic.socialnetwork', verbose_name='Соц. сети'),
        ),
    ]
