# Generated by Django 5.2.1 on 2025-05-21 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0014_doctor_accepts_online_doctor_appointments_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='slug',
            field=models.SlugField(blank=True, verbose_name='URL'),
        ),
    ]
