# Generated by Django 5.2.1 on 2025-05-21 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0017_remove_doctor_specialization_doctor_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя пациента')),
                ('stars', models.PositiveSmallIntegerField(default=5, verbose_name='Оценка (звезды)')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('image', models.ImageField(blank=True, null=True, upload_to='testimonials/', verbose_name='Фото пациента')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinic.departments', verbose_name='Отделение')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinic.doctor', verbose_name='Врач')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
