# Generated by Django 5.2.1 on 2025-05-23 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0019_testimonial_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clinic.departments', verbose_name='Отделение'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='doctor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clinic.doctor', verbose_name='Врач'),
            preserve_default=False,
        ),
    ]
