# Generated by Django 5.2.1 on 2025-05-23 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0020_alter_testimonial_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departments',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='title',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
    ]
