# Generated by Django 5.2.1 on 2025-05-26 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0023_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='appointments_url',
            field=models.CharField(blank=True, null=True, verbose_name='Ссылка на запись'),
        ),
    ]
