# Generated by Django 5.2.1 on 2025-05-26 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0024_alter_doctor_appointments_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'Галерея', 'verbose_name_plural': 'Фото'},
        ),
    ]
